Update build-Alvin9999.yml

diff --git a/.github/workflows/build-Alvin9999.yml b/.github/workflows/build-Alvin9999.yml
--- a/.github/workflows/build-Alvin9999.yml
+++ b/.github/workflows/build-Alvin9999.yml
@@ -9,6 +9,10 @@ on:
 permissions:
   contents: write  # 允许写入仓库内容
 
+env:
+  UPDATE_PY: Alvin9999/update.py
+  UPDATE_MD: Alvin9999/update.md
+  
 jobs:
   update-wiki-readme:
     runs-on: ubuntu-latest
@@ -19,11 +23,6 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
-
-      # 2. 克隆 Wiki 仓库到 wiki 目录
-      #- name: Checkout Wiki Repository
-      #  run: |
-      #    git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/seacdr/AX6-OpenWRT.git wiki
           
       # 3. 设置 Python 环境
       - name: Set up Python
@@ -39,14 +38,23 @@ jobs:
       # 5. 运行更新脚本        
       - name: Run Update Script
         run: |
-          rm -rf Alvin9999/UPDATE.md
-          python Alvin9999/update.py
+          rm -f ${{ env.UPDATE_MD }}
+          python ${{ env.UPDATE_PY }}
 
       # 6. 提交和推送更新到主仓库
-      - name: Commit and Push Alvin9999 Updates
+      - name: Commit and Push Updates
         run: |
-          git config --local user.name "github-actions"
-          git config --local user.email "actions@github.com"
-          git add Alvin9999/UPDATE.md
-          git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')"
-          git push
+          if [[ -f "${{ env.UPDATE_MD }}" ]]; then
+            git config --local user.name "github-actions"
+            git config --local user.email "actions@github.com"
+            git add ${{ env.UPDATE_MD }}
+            if ! git diff --cached --quiet; then
+              git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')"
+              git push
+            else
+              echo "No changes detected"
+            fi
+          else
+            echo "Error: ${{ env.UPDATE_MD }} not generated"
+            exit 1
+          fi
